# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

###growth classes (mediums)
GrowthClass.create(name: 'Hydroponic')
GrowthClass.create(name: 'Soil')
GrowthClass.create(name: 'Aquaponic')

###herbs
Plant.create(name: 'Basil', description: '', pH: 6.0, ec: 1.3, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Chicory', description: '', pH: 5.75, ec: 2.2, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Chives', description: '', pH: 6.25, ec: 2.1, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Fennel', description: '', pH: 6.6, ec: 1.2, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Lavender', description: '', pH: 6.6, ec: 1.2, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Lemon Balm', description: '', pH: 6.0, ec: 1.3, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Marjoram', description: '', pH: 6.0, ec: 1.8, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Mint', description: '', pH: 5.75, ec: 2.2, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Mustard Cress', description: '', pH: 6.25, ec: 1.8, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Parsley', description: '', pH: 5.75, ec: 1.3, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Rosemary', description: '', pH: 5.75, ec: 1.3, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Sage', description: '', pH: 6.0, ec: 1.0, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'Thyme', description: '', pH: 6.25, ec: 1.2, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
Plant.create(name: 'WaterCress', description: '', pH: 6.6, ec: 1.1, plant_notes: 'As a general rule, plants will have a higher nutrient requirement during cooler months, and a lower requirement In the hottest months. Therefore, a stronger nutrient solution should be maintained during winter, With a weaker solution during summer when plants take up and transpire more water than nutrients.', growth_class_id: 1)
